/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  TokenInfoController,
  TokenInfoControllerInterface,
} from "../TokenInfoController";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_account",
        type: "address",
      },
      {
        name: "_spender",
        type: "address",
      },
    ],
    name: "get_allowance",
    outputs: [
      {
        name: "_allowance",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_user",
        type: "address",
      },
    ],
    name: "get_balance",
    outputs: [
      {
        name: "_actual_balance",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "get_total_supply",
    outputs: [
      {
        name: "_total_supply",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6060604052341561000f57600080fd5b61017e8061001e6000396000f300606060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063188369941461005c5780631e279a37146100c8578063f923058c14610115575b600080fd5b341561006757600080fd5b6100b2600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803573ffffffffffffffffffffffffffffffffffffffff1690602001909190505061013e565b6040518082815260200191505060405180910390f35b34156100d357600080fd5b6100ff600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610146565b6040518082815260200191505060405180910390f35b341561012057600080fd5b61012861014d565b6040518082815260200191505060405180910390f35b600092915050565b6000919050565b6000905600a165627a7a7230582050979f34415a4248b549e2aa550ca8164a7bbf1b5d170ce52a1db10c295ef6000029";

export class TokenInfoController__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TokenInfoController> {
    return super.deploy(overrides || {}) as Promise<TokenInfoController>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TokenInfoController {
    return super.attach(address) as TokenInfoController;
  }
  connect(signer: Signer): TokenInfoController__factory {
    return super.connect(signer) as TokenInfoController__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TokenInfoControllerInterface {
    return new utils.Interface(_abi) as TokenInfoControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenInfoController {
    return new Contract(address, _abi, signerOrProvider) as TokenInfoController;
  }
}
