/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Ownable, OwnableInterface } from "../Ownable";

const _abi = [
  {
<<<<<<< HEAD
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
=======
>>>>>>> dev1
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
<<<<<<< HEAD
    constant: true,
    inputs: [],
    name: "isOwner",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
=======
>>>>>>> dev1
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
<<<<<<< HEAD
    payable: false,
=======
>>>>>>> dev1
    stateMutability: "view",
    type: "function",
  },
  {
<<<<<<< HEAD
    constant: false,
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    payable: false,
=======
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
>>>>>>> dev1
    stateMutability: "nonpayable",
    type: "function",
  },
  {
<<<<<<< HEAD
    constant: false,
=======
>>>>>>> dev1
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
<<<<<<< HEAD
    payable: false,
=======
>>>>>>> dev1
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Ownable__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableInterface {
    return new utils.Interface(_abi) as OwnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Ownable {
    return new Contract(address, _abi, signerOrProvider) as Ownable;
  }
}
