/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { TokenReceiver, TokenReceiverInterface } from "../TokenReceiver";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "from",
        type: "address",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "data",
        type: "bytes32",
      },
    ],
    name: "tokenFallback",
    outputs: [
      {
        name: "success",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TokenReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): TokenReceiverInterface {
    return new utils.Interface(_abi) as TokenReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenReceiver {
    return new Contract(address, _abi, signerOrProvider) as TokenReceiver;
  }
}
