/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ResolverClientInterface extends ethers.utils.Interface {
  functions: {
    "resolver()": FunctionFragment;
    "key()": FunctionFragment;
    "get_contract(bytes32)": FunctionFragment;
    "destroy()": FunctionFragment;
    "CONTRACT_ADDRESS()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "resolver", values?: undefined): string;
  encodeFunctionData(functionFragment: "key", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "get_contract",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "destroy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CONTRACT_ADDRESS",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "resolver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "key", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "get_contract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "destroy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CONTRACT_ADDRESS",
    data: BytesLike
  ): Result;

  events: {};
}

export class ResolverClient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ResolverClientInterface;

  functions: {
    resolver(overrides?: CallOverrides): Promise<[string]>;

    key(overrides?: CallOverrides): Promise<[string]>;

    get_contract(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { _contract: string }>;

    destroy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    CONTRACT_ADDRESS(overrides?: CallOverrides): Promise<[string]>;
  };

  resolver(overrides?: CallOverrides): Promise<string>;

  key(overrides?: CallOverrides): Promise<string>;

  get_contract(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  destroy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  CONTRACT_ADDRESS(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    resolver(overrides?: CallOverrides): Promise<string>;

    key(overrides?: CallOverrides): Promise<string>;

    get_contract(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    destroy(overrides?: CallOverrides): Promise<boolean>;

    CONTRACT_ADDRESS(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    resolver(overrides?: CallOverrides): Promise<BigNumber>;

    key(overrides?: CallOverrides): Promise<BigNumber>;

    get_contract(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    destroy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    CONTRACT_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    resolver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    key(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    get_contract(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    destroy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    CONTRACT_ADDRESS(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
