/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TokenInfoControllerInterface extends ethers.utils.Interface {
  functions: {
    "get_allowance(address,address)": FunctionFragment;
    "get_balance(address)": FunctionFragment;
    "get_total_supply()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "get_allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "get_balance", values: [string]): string;
  encodeFunctionData(
    functionFragment: "get_total_supply",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "get_allowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_balance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_total_supply",
    data: BytesLike
  ): Result;

  events: {};
}

export class TokenInfoController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TokenInfoControllerInterface;

  functions: {
    get_allowance(
      _account: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _allowance: BigNumber }>;

    get_balance(
      _user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _actual_balance: BigNumber }>;

    get_total_supply(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _total_supply: BigNumber }>;
  };

  get_allowance(
    _account: string,
    _spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  get_balance(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

  get_total_supply(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    get_allowance(
      _account: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get_balance(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    get_total_supply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    get_allowance(
      _account: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get_balance(_user: string, overrides?: CallOverrides): Promise<BigNumber>;

    get_total_supply(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    get_allowance(
      _account: string,
      _spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get_balance(
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get_total_supply(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
